# Cloudflare Wrangler Configuration File
# Read more: https://developers.cloudflare.com/workers/wrangler/configuration/

name = "sorat-cloudflare-worker"
main = "worker.ts"
compatibility_date = "2024-01-01"

# Cloudflare D1 Serverless SQL Database Binding
[[d1_databases]]
binding = "DB"
database_name = "sorat-d1-db"
database_id = "your-d1-database-uuid-goes-here"
